language: elixir
elixir:
- 1.7.2
otp_release:
- 21.1.3
script:
- mix format --check-formatted
- mix test
- mix credo
- MIX_ENV=prod mix release --quiet
before_deploy:
- openssl aes-256-cbc -K $encrypted_a77158a5a442_key -iv $encrypted_a77158a5a442_iv
  -in travis_rsa.enc -out /tmp/travis_rsa -d
- chmod 600 /tmp/travis_rsa
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
env:
  global:
  - secure: x6miQ6Y9dJTcHWPD+0XaDngXjISK+UZYl690/q3C3K1QdImkoCqhVuHIRuBQ5Ws+22C5bUdQQjLE5FpQS5LSJ712DZRlWEjeIkp6Dow576i/B+LZpntUf/9KOFXiA2La7P9lKBQqnAYRcfdWRcc5fz63uEya0Vs7FENPBH6Ag47uZ6v3ck9lD//bz+hd1ePpfHGPJS17BsHQCBHz/kti7ICUKVdOOeJUAdv8QRP9V+94y8c2uDglCgdnZldZ+KbrE/Q/GO7ChC9t0q6aY6wDYF9ZSRONlR4cdr+nJ9sJcdA46m7EKthAWvvO7gqhKV+oupMZBR299rPf4Rn5qWP6bljUBHSOjy/a7Xf18qtYHQ7SSi2O+n9TZ1/ZY7nomBqseWJUplR+YKENS8VN5MN/4NJW7K5ShyBtUOgXXdr/Y/QgFaLxkVD1NIIRGpZu/hIxthXeDoo9W7STqJp0Sasz7J62Lq+a374HlkJfPICoM4MgEH51HJzFCkqNEvBVOGix20hnk16wvKt4H1hLAg6J/VYIXIpCkVh0XPvat9JzFartc1fQcZMq1Kt/EEnAtOGWqMTs2amXzULu0XoCrO8XkLSqJmXhyRFLuWkndGmChJggsJheuicN676uztWI5XtZsOKqLCjPoS3Vz1+49EovYLOSThpqT7+ClaiorSibl5o=
  - secure: Yaq0jcRXu+jXZsJS24s/mxpHR9N2FVcdjwuCxx7XhMGclqTVeeVI5PlK1JngXXbRzPJfzsfIrSQUK8inWj2FJ7l7CBHGmrV11orLCih9OD3wCGcrhHc/Bg1Yv+3GRlq+L0w5trme0Kh3ZLb8zY6jTUZ0Fguekh7zCW4l9ddsaOssANIoP3BBB9BSW1Myup9TLnQ6lsOs4M0Q43QJwXW7UrnVna3HX9oEf7ooKsyGehvYqpyTVgik+IWdhA+HQdbYElXqIgyAUJXnyvxff+0BZvpgR2kv5nJj5sVZvJnM1RCCPe07xjIfDOdC6U+62Gw2TF4W+L80/IaYCTO/yHQBO0emBN/fozxVvOGXWh911t0ltyb+mw5JTUqkLC2tFvolH08rd41cLQr89+u+cKTtQ7Aabp0ypGUemtRJBMeWXpCOHjzMzzsQiJ1BwL+mqD2IrNQw3SV8XzToNC0SkqNgv4zdxR1X2WQjGskZbMMgrnUlEQyyMzELfyeSxxDW7Jj3Tzx6CQSccPK5PF5GsdV8cum/UYbTqr1hTHCYR6AOSGVPAlJvDzvct/Ory8VmrbjmyaPPfIfhngJXJ+4FKV3NvCAxqzk5hCCpYnkVw4ILCbJsFHF/3uY/IAjPjMnjrIgAkOC82QU3VMgzjBFk5cwOFHytFBB51xJhEQbJaHVAlzs=
