language: elixir
elixir:
- 1.7.2
otp_release:
- 21.1.3
before_deploy:
- openssl aes-256-cbc -K $encrypted_a77158a5a442_key -iv $encrypted_a77158a5a442_iv
  -in travis_rsa.enc -out /tmp/travis_rsa -d
- chmod 600 /tmp/travis_rsa
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
